<?php
    $this->filterForm->prepare();
    echo $this->form($this->filterForm);
?>
<?php
    $editUrl = $this->url('simple-crud/default', array('controller' => 'barang', 'action' => 'edit'));
    $deleteUrl = $this->url('simple-crud/default', array('controller' => 'barang', 'action' => 'delete'));

?>
<a href="<?php echo $this->url('simple-crud/default', array('controller' => 'barang', 'action' => 'entry')) ?>" class="btn btn-primary">Tambah Barang</a>
<?php echo $paginationHtml = $this->customPaginationControl($this->paginator) ?>
<br class="clear" />
<br class="clear" />
<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <th style="width: 30px">No</th>
            <th style="width: 130px">Kode</th>
            <th style="width: 130px">Nama</th>
            <th style="width: 130px">Satuan</th>
            <th style="width: 130px">Harga</th>
            <th>Keterangan</th>
            <th style="width: 130px"></th>
        </tr>
    </thead>
    <tbody>
        <?php
            $no = 1; 
            foreach($this->paginator as $barang): 
        ?>
        <tr>
            <td><?php echo $this->paginator->getAbsoluteItemNumber($no); ?></td>
            <td><?php echo $this->escapeHtml($barang->getKode()) ?></td>
            <td><?php echo $this->escapeHtml($barang->getNama()) ?></td>
            <td><?php echo $this->escapeHtml($barang->getSatuan()) ?></td>
            <td><?php echo $this->escapeHtml($barang->getHarga()) ?></td>
            <td><?php echo $this->escapeHtml($barang->getKeterangan()) ?></td>
            <td><a href="<?php echo $editUrl ?>?id=<?php echo $this->escapeHtml($barang->getId()) ?>">Edit</a> | <a href="<?php echo $deleteUrl ?>?id=<?php echo $this->escapeHtml($barang->getId()) ?>">Delete</a></td>
        </tr>
        <?php $no++; endforeach; ?>
    </tbody>
</table>
